language: objective-c
osx_image: xcode9.4

script:
    - xcrun simctl list
    - xcodebuild -project XCKnifeExemplar.xcodeproj -configuration Debug -scheme XCKnifeExemplar -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPad Air,OS=11.2" test
